# Site settings
title: Samwalker Cheng
email: samwalker505@gmail.com
url: https://www.facebook.com/samwalker505
description: "Samwalker Cheng's personal website, come and discover me"
skills: "Web Developer - Andriod Developer - Eater - TaoBaoer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5E4485
  primary-rgb: "94,68,133"
  secondary: 171714
  secondary-dark: 233140 #A2122F

profile:
  size: 280

# Footer settings
footer:
  copyright: Samwalker Cheng
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/samwalker505
  - title: bitbucket
    url: http://bitbucket.org/samwalker
  - title: github
    url: http://github.com/samwalker505

# Postal address (add as many lines as necessary)
address:
  - line: Kam Tai Court
  - line: Ma On Shan, NT, Hong Kong

# Credits content
credits: 'Hi, this website is base on Freelancer. Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
